# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd6aea1d60b9c829c73645a9e48aed8710d4249940e3ebe5df0c5daee9cf613bdfd73d10db27c0ecf054f5a90c8dbc5b7e4891c53636833af0f269884d07ae2

test:
  secret_key_base: 350bad271ecd55cb894da6de082a2326f2ebfb2614b265abe6da13e956f4ba16fe022b0084b870f0fdcbe24c28f3cc7bad73da037f0fa2523164947492f70097

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
